### PR TITLE
update grammar

### LINKED ISSUE #13: Grammer in README.md
It's currently Teaches Web Development, would it be better if it is Makes Tutorials on Web Development?

What do you think on this @vikasganiga05 @AnimeshKumar923?

### PR DESCRIPTION
**Pull request by KendallDoesCoding**
fixes #13 

as per @AnimeshKumar923 's suggestions in #13.

### CODE REVIEW

**Comment by KendallDoesCoding** [comment]
@AnimeshKumar923 please review at the earliest.

**Review by AnimeshKumar923 — APPROVED** [review]
Looks good👍🏻

**Comment by KendallDoesCoding** [comment]
Merging to main.

**Comment by KendallDoesCoding** [comment]
> Looks good👍🏻

Commited to main. 

Reminder: please join organization so I can request you to review anything related to grimmer.

**Pull request closed without merging**
