### PR TITLE
Added Fireship & Bengali YouTubers.

### PR DESCRIPTION
**Pull request by fluentmoheshwar**
Fireship is a great English channel that makes awesome content. I also added bengali youtubers to help bengalis like me.

### CODE REVIEW

**Review by KendallDoesCoding — APPROVED** [review]

**Comment by KendallDoesCoding** [comment]
Hi @fluentmoheshwar ,

Thanks for your contribution.. Merging!

**Comment by KendallDoesCoding** [comment]
Hi, you didn't tell you were changing the website theme also, but it looks better now ig. Thanks!

**Comment by fluentmoheshwar** [comment]
> Hi, you didn't tell you were changing the website theme also, but it looks better now ig. Thanks!

I thought that it will only affect my fork.

**Comment by KendallDoesCoding** [comment]
> > Hi, you didn't tell you were changing the website theme also, but it looks better now ig. Thanks!
> 
> I thought that it will only affect my fork.

No worries, for now let it be, I've asked the mod team of this project, which theme they like the best.

**Pull request merged**
