### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by ShubhamJagtap2000**
Added MyCodeSchool YouTube channel in README.md of main repo.

### CODE REVIEW

**Comment by adityajoshi-08** [comment]
Hi Shubham! Can you please add the channel in respective repo?

**Comment by ShubhamJagtap2000** [comment]
> Hi Shubham! Can you please add the channel in respective repo?

Changes have been made to the DSA directory. Please review. I am active in Hacktoberfest, can you assign its label too? If not will also be fine.

**Comment by adityajoshi-08** [comment]
Don't worry, I will add the labels and merge the PR after review! Thanks for contribution❤️

**Comment by ShubhamJagtap2000** [comment]
> Don't worry, I will add the labels and merge the PR after review! Thanks for contribution❤️

Sure, sure Aditya.

**Review by adityajoshi-08 — APPROVED** [review]
Looks good. No conflicts.

**Pull request merged**
