### PR TITLE
table headers in bold

### LINKED ISSUE #33: Header of Table not Bold on Website.
The header of table, "Name", "Description" & "Language" are not bold on the website for some reason.

I require someone to fix this issue at the earliest.

@Agrim-Sharma174 please have a look.

### PR DESCRIPTION
**Pull request by nettle790**
fixes #33 

BY default the table headers are bold but applying the changes in css file makes the headers in uppercase also.

### CODE REVIEW

**Comment by nettle790** [comment]
the text-transform property in css will make your table headers in bold and uppercase letters.

**Comment by nettle790** [comment]
referring to good first issue #33

**Comment by KendallDoesCoding** [comment]
Sure. Ig this will work.

**Comment by nettle790** [comment]
To specify for top heading row jus specify as follows
Table,th {
    }

Hope this helps

**Comment by KendallDoesCoding** [comment]
Please make a PR.

**Comment by KendallDoesCoding** [comment]
Oh, the PR is already open, my bad.

**Review by KendallDoesCoding — APPROVED** [review]

**Comment by KendallDoesCoding** [comment]
Please review at the earliest @Agrim-Sharma174 to confirm if this will work.

**Review by Agrim-Sharma174 — APPROVED** [review]
Approved

**Pull request merged**
