### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by AnimeshKumar923**
-fixed typos and grammar
-fixed aesthetics of the document to provide the reader with more ease of reading
-made bold the concepts/topics taught
-added Kunal Kushwaha to the list
-added Eddie Jaoude to the list

### CODE REVIEW

**Review by KendallDoesCoding — APPROVED** [review]

**Comment by KendallDoesCoding** [comment]
@AnimeshKumar923 Please resolve merge conflict, I can't figure out what the issue is.

cc: @vikasganiga05 @Adarsh-jaiss @Vrashabh-Sontakke

**Comment by AnimeshKumar923** [comment]
@KendallDoesCoding Hey, I'm unable to understand what is the conflict here. Can you guide me please?

**Comment by AnimeshKumar923** [comment]
@KendallDoesCoding Hey Kendall, I think the previous closed PR by @LalitDhane is conflicting with mine. What should we do about that?

**Comment by KendallDoesCoding** [comment]
> @KendallDoesCoding Hey Kendall, I think the previous closed PR by @LalitDhane is conflicting with mine. What should we do about that?

Yes. Same. Can you redo the changes in a new branch and make a new PR. Sorry about the inconvenience. I should've merged yours first as yours had more changes then @LalitDhane 's.

**Comment by AnimeshKumar923** [comment]
@KendallDoesCoding closing this PR. Will open another to update the list

**Comment by KendallDoesCoding** [comment]
Thanks. Again, sorry for the inconvenience. I can just do the changes but I
want you marked as a contributor so you get green squares on your profile
:))

**Comment by KendallDoesCoding** [comment]
Please open a new PR @AnimeshKumar923

**Comment by KendallDoesCoding** [comment]
@AnimeshKumar923 , I'll make the PR.

**Comment by KendallDoesCoding** [comment]
I've made you the co-author so the commits are traced back to you as well, please review #12 .. Also, make sure you join our organization by creating a issue in become-a-member, @AnimeshKumar923

**Comment by AnimeshKumar923** [comment]
@KendallDoesCoding Hello Kendall, sorry for the late reply, was busy with something.

Thank you for making me the co-author and reopening the PR.

I was trying to improve just a little bit but not too much as I'm very new to contributing here so want to take it one step at a time. LalithDhane's PR has major changes and is a bit lengthy to read. 

I wanted it to be short and concise so that the seekers can get to work ASAP.

I little bit about myself:

-just graduated from school.
-will start college in a month from now.
-new to open source and don't know much about coding and learning it slowly.
-good with grammar and related stuff.

I'll be working on other open issues at later time.

Would be happy to join the organisation, please give a detailed process for joining.

Thank you!

**Comment by KendallDoesCoding** [comment]
Hi @AnimeshKumar923 , no worries!

Ofcourse, I thought you may've been having a difficulty reopening!

> I was trying to improve just a little bit but not too much as I'm very new to contributing here so want to take it one step at a time. LalithDhane's PR has major changes and is a bit lengthy to read.


> I wanted it to be short and concise so that the seekers can get to work ASAP.

You did a amazing job with your PR!

> About the green squares, it isn't primary goal but it yes it helps. Main focus is to helping to solve issues and making progress.

exactly!

> I little bit about myself:

-just graduated from school.
-will start college in a month from now.
-new to open source and don't know much about coding and learning it slowly.
-good with grammar and related stuff.

oh cool! do you have discord? you can join our community and talk to us, we'll surely assist you if you need any help.

> I'll be working on other open issues at later time.

😄 - Thanks for your support!

> Would be happy to join the organisation.

Please create a issue in https://github.com/collab-community/become-a-member

Thank you,
Kendall

**Comment by AnimeshKumar923** [comment]
Thank you for the feedback! It means a lot as a newbie. @KendallDoesCoding

**Comment by KendallDoesCoding** [comment]
> Thank you for the feedback! It means a lot as a newbie. @KendallDoesCoding

Welcome! Always happy to help. Even I just started open source quite recently actually.

**Pull request closed without merging**
