### PR TITLE
Categorized the YouTube Channels in README

### LINKED ISSUE #7: [FEAT] Categorize the YouTube Channels
It will be good to categorize the YouTube channels by video language, topics, everyday uploads, etc.

> For Example :point_down: 

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Language</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>
        <strong><a href="https://youtube.com/c/Freecodecamp">freeCodeCamp.org</a></strong>
      </td>
      <td>All types of coding video.</td>
      <td>English</td>
    </tr>
    <tr>
      <td>
        <strong><a href="https://youtube.com/c/KunalKushwaha">Kunal Kushwaha</a></strong>
      </td>
      <td>Empowering communities via open-source and education.</td>
      <td>English, Hindi</td>
    </tr>
  </tbody>
</table>

> Code for the above table :point_down: 

```html
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Language</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>
        <strong><a href="https://youtube.com/c/Freecodecamp">freeCodeCamp.org</a></strong>
      </td>
      <td>All types of coding video.</td>
      <td>English</td>
    </tr>
    <tr>
      <td>
        <strong><a href="https://youtube.com/c/KunalKushwaha">Kunal Kushwaha</a></strong>
      </td>
      <td>Empowering communities via open-source and education.</td>
      <td>English, Hindi</td>
    </tr>
  </tbody>
</table>
```

### PR DESCRIPTION
**Pull request by Agrim-Sharma174**
fixes #7 

Created the table of the Youtube channel's Names, its description, and the language it is in.

### CODE REVIEW

**Review by KendallDoesCoding — APPROVED** [review]

**Comment by KendallDoesCoding** [comment]
Looks amazing, let Vikas review.

**Review by vikasganiga05 — APPROVED** [review]
Yes, It's looking good to me :+1: 
We need to add contribution guidelines for adding a new youtube channel.

**Comment by KendallDoesCoding** [comment]
> We need to add contribution guidelines for adding a new youtube channel.

Please make a issue on this, without assigning anyone with the label, EddieHub:good-first-issue and good-first-issue also documentation. Thanks

**Comment by KendallDoesCoding** [comment]
Thanks a lot @Agrim-Sharma174

**Pull request merged**
