### PR TITLE
Resources for DSA added

### PR DESCRIPTION
**Pull request by adityajoshi-08**
Resources for DSA have been added. These cover most of the syllabus. I'll be adding more as soon as I get more!

### CODE REVIEW

**Review by Adarsh-jaiss — APPROVED** [review]

**Comment by Adarsh-jaiss** [comment]
Looks good to me :)

**Review by KendallDoesCoding — CHANGES_REQUESTED** [review]
Couple of things

Firstly, I request you to follow the same template as the main README.md, with first the Channel name (hyperlink their YT channel link/playlist), then the description and then the language.

Secondly, please link the file with one small sentence in the README.md:

**YouTubers for learning DSA** hyperlink the README file you created in the DSA directory.

**Comment by KendallDoesCoding** [comment]
Also, why are we only doing this for DSA, should'nt we do it for all coding languages/catergories @collab-community/coding-youtubers?

**Review by fluentmoheshwar — CHANGES_REQUESTED** [review]
Use the new table formatting.

**Comment by adityajoshi-08** [comment]
Okay!

**Pull request closed without merging**
