### PR TITLE
Add banner

### PR DESCRIPTION
**Pull request by KendallDoesCoding**
I've added a banner created by https://socialify.git.ci to the README.md file.

Please review at the earliest @collab-community/coding-youtubers

### CODE REVIEW

**Review by vikasganiga05 — CHANGES_REQUESTED** [review]
My suggestion is to make the header image full width. What are your thoughts on this Kendall?

**Comment by KendallDoesCoding** [comment]
> My suggestion is to make the header image full width. What are your thoughts on this Kendall?

I made it small on purpose, because the focus of this is to see the YouTube channels, and the banner covers it a lot, I want it to be the best user experience so as to not make them scroll down extra. I was gonna make the banner smaller then this, but decided not to.

**Review by Agrim-Sharma174 — APPROVED** [review]
Looks good to me!

**Review by vikasganiga05 — APPROVED** [review]
Yes, I agree with you Kendall. Let's add this header image to the readme.

**Pull request merged**
